project_id = "leplvqapnexpgmivfdpl"

[functions.seed_demo]
verify_jwt = false

[functions.admin-user-management]
verify_jwt = false

[functions.set-admin-password]
verify_jwt = false

[functions.send-document-webhook]
verify_jwt = true

[functions.receive-ai-insights-webhook]
verify_jwt = false

[functions.send-signup-email]
verify_jwt = false

[functions.connect-google-drive]
verify_jwt = false

[functions.connect-slack]
verify_jwt = false

[functions.connect-hubspot]
verify_jwt = false

[functions.generate-ai-insights]
verify_jwt = false

[functions.generate-task-summary]
verify_jwt = false